--- # Bootstrap Webservers
- hosts: centos
  become: yes
  gather_facts: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    notify:
      - restart httpd
  - name: create index.html file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
      line: "This is the beginning of a new chapter"
      path: /var/www/html/index.html
    notify:
      - restart httpd
  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
